---
#Setup load-balance server

- name: install haproxy
  yum:
    name: "{{ payload }}"
    state: present
  tags:
    - install_haproxy

- name: configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy
  tags:
    - configure_haproxy

- name: enable haproxy
  service:
    name: "{{ payload }}"
    enabled: true 
    state: started
  tags:
    - enable_haproxy
